///|
test "open" {
  @async.start!(fn() {
    @async.path!("moon.mod.json").open!(ReadOnly).text!()
    |> @json.parse!()
    |> @json.inspect!(content={
      "name": "tonyfettes/uv",
      "version": "0.2.0",
      "deps": { "tonyfettes/c": "0.1.13", "tonyfettes/encoding": "0.3.0" },
      "readme": "README.md",
      "repository": "https://github.com/tonyfettes/uv.mbt",
      "license": "Apache-2.0",
      "keywords": [],
      "description": "MoonBit binding to libuv",
      "source": "src",
    })
  })
}

test "scandir" {
}
